services:
  - type: web
    name: mehrozkiyad-bot
    env: python
    pythonVersion: "3.12.15"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot_app.py"
envVars:
  - key: BOT_TOKEN
    sync: false
  - key: WEBHOOK_URL
    sync: false

